In [1]:
import pandas as pd

In [2]:
# load cleaned data
df = pd.read_csv('../data/processed/cleaned_complaints.csv')

In [3]:
df.head()

,Unnamed: 0,SR Number,Date/Time Opened,Service Request Address,Service Request Status,Answer,street_address,zipcode,apt_num,datetime_opened,year,month_year,date,hour,city,state
0,0,SR18-00198455,12/19/18 02:53 PM,NaN,Completed,No Cause,NaN,NaN,,2018-12-19 14:53:00,2018,12/2018,2018-12-19,14,Chicago,Illinois
1,1,SR19-01043676,02/20/19 01:40 PM,1135 N Harlem AVE<br> 60302,Completed,No Cause,1135 N Harlem AVE,60302.0,,2019-02-20 13:40:00,2019,02/2019,2019-02-20,13,Chicago,Illinois
2,2,SR19-01047333,02/21/19 08:56 AM,18231 S Sayre AVE<br> 60477,Completed,No Cause,18231 S Sayre AVE,60477.0,,2019-02-21 08:56:00,2019,02/2019,2019-02-21,8,Chicago,Illinois
3,3,SR19-01050631,02/21/19 03:29 PM,6726 N SHERIDAN RD<br> 60626,Completed,Processed for Hearing - Standard,6726 N SHERIDAN RD,60626.0,,2019-02-21 15:29:00,2019,02/2019,2019-02-21,15,Chicago,Illinois
4,4,SR19-01058995,02/23/19 11:35 AM,2746 N 74th AVE<br> 60707,Completed,No Cause,2746 N 74th AVE,60707.0,,2019-02-23 11:35:00,2019,02/2019,2019-02-23,11,Chicago,Illinois

In [5]:
# identify the four complaints with no address
df[df['street_address'].isnull()]

,Unnamed: 0,SR Number,Date/Time Opened,Service Request Address,Service Request Status,Answer,street_address,zipcode,apt_num,datetime_opened,year,month_year,date,hour,city,state
0,0,SR18-00198455,12/19/18 02:53 PM,NaN,Completed,No Cause,NaN,NaN,,2018-12-19 14:53:00,2018,12/2018,2018-12-19,14,Chicago,Illinois
6,6,SR19-01068011,02/25/19 11:47 AM,NaN,Completed,No Cause,NaN,NaN,,2019-02-25 11:47:00,2019,02/2019,2019-02-25,11,Chicago,Illinois
5712,5712,SR21-00217372,02/08/21 08:20 AM,NaN,Completed,No Cause,NaN,NaN,,2021-02-08 08:20:00,2021,02/2021,2021-02-08,8,Chicago,Illinois
5714,5714,SR21-00217555,02/08/21 08:56 AM,NaN,Completed,No Cause,NaN,NaN,,2021-02-08 08:56:00,2021,02/2021,2021-02-08,8,Chicago,Illinois
5726,5726,SR21-00217933,02/08/21 09:44 AM,NaN,Completed,No Cause,NaN,NaN,,2021-02-08 09:44:00,2021,02/2021,2021-02-08,9,Chicago,Illinois

## Remove duplicate SR Numbers

These are duplicate versions of the same calls that mostly got recategorized as different violations such as ventilation, electrical, plumbing etc.

In [6]:
# identify 249 rows of duplicates
duplicates_mask = df.duplicated(subset=['SR Number'],keep=False)
df[duplicates_mask]

,Unnamed: 0,SR Number,Date/Time Opened,Service Request Address,Service Request Status,Answer,street_address,zipcode,apt_num,datetime_opened,year,month_year,date,hour,city,state
191,191,SR19-01119959,03/07/19 10:03 AM,1053 W GRANVILLE AVE<br> 60660,Completed,Transfer to Ventilation Violation,1053 W GRANVILLE AVE,60660.0,,2019-03-07 10:03:00,2019,03/2019,2019-03-07,10,Chicago,Illinois
192,192,SR19-01119959,03/07/19 10:03 AM,1053 W GRANVILLE AVE<br> 60660,Completed,No Cause,1053 W GRANVILLE AVE,60660.0,,2019-03-07 10:03:00,2019,03/2019,2019-03-07,10,Chicago,Illinois
348,348,SR19-01225744,03/26/19 05:37 PM,9351 S RACINE AVE<br> 60620,Completed,Transfer to Ventilation Violation,9351 S RACINE AVE,60620.0,,2019-03-26 17:37:00,2019,03/2019,2019-03-26,17,Chicago,Illinois
349,349,SR19-01225744,03/26/19 05:37 PM,9351 S RACINE AVE<br> 60620,Completed,No Entry,9351 S RACINE AVE,60620.0,,2019-03-26 17:37:00,2019,03/2019,2019-03-26,17,Chicago,Illinois
501,501,SR19-01380156,04/24/19 02:01 PM,2 E 8TH ST<br> 60605,Completed,Transfer to Ventilation Violation,2 E 8TH ST,60605.0,,2019-04-24 14:01:00,2019,04/2019,2019-04-24,14,Chicago,Illinois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16351,16351,SR24-00105674,01/18/24 08:14 AM,6811 S PAXTON AVE<br>,Completed,No Entry,6811 S PAXTON AVE,NaN,,2024-01-18 08:14:00,2024,01/2024,2024-01-18,8,Chicago,Illinois
16391,16391,SR24-00110455,01/18/24 05:55 PM,1343 N CLEVELAND AVE<br>Chicago Illinois 60610,Completed,Transfer to Boiler Violation,1343 N CLEVELAND AVE,60610.0,Chicago Illinois,2024-01-18 17:55:00,2024,01/2024,2024-01-18,17,Chicago,Illinois
16392,16392,SR24-00110455,01/18/24 05:55 PM,1343 N CLEVELAND AVE<br>Chicago Illinois 60610,Completed,No Cause,1343 N CLEVELAND AVE,60610.0,Chicago Illinois,2024-01-18 17:55:00,2024,01/2024,2024-01-18,17,Chicago,Illinois
16570,16570,SR24-00138578,01/23/24 05:08 PM,1561 N FREMONT ST<br>,Completed,Transfer to Ventilation Violation,1561 N FREMONT ST,NaN,,2024-01-23 17:08:00,2024,01/2024,2024-01-23,17,Chicago,Illinois
16571,16571,SR24-00138578,01/23/24 05:08 PM,1561 N FREMONT ST<br>,Completed,NaN,1561 N FREMONT ST,NaN,,2024-01-23 17:08:00,2024,01/2024,2024-01-23,17,Chicago,Illinois

In [7]:
# remove duplicates by keeping first instance only in df
df.drop_duplicates(subset=['SR Number'], keep='first', inplace=True)

In [8]:
# export deduplicated dataframe
df.to_csv('../data/processed/cleaned_complaints_deduplicated.csv')